using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LeaveWizard
{
    public partial class LeaveChart
    {
        public List<WeekData> Weeks = new List<WeekData>();
        public int CurrentWeek = 0;
        
        public IEnumerable<WeekData> EnumerateWeeks(DateTime StartDate, DateTime EndDate)
        {
            var currentWeek = 0;

            while (true)
            {
                if (currentWeek >= Weeks.Count) break;
                var previousWeek = (currentWeek == 0 ? null : Weeks[currentWeek - 1]);
                Weeks[currentWeek].Propogate(previousWeek);
                if (Weeks[currentWeek].SaturdayDate > EndDate) break;
                if (Weeks[currentWeek].SaturdayDate + TimeSpan.FromDays(7) > StartDate) yield return Weeks[currentWeek];
                currentWeek += 1;
            }
        }

        public IEnumerable<DailySchedule> EnumerateDays(DateTime StartDate, DateTime EndDate)
        {
            foreach (var week in EnumerateWeeks(StartDate, EndDate))
            {
                for (var day = 0; day < 7; ++day)
                    if (week.SaturdayDate + TimeSpan.FromDays(day) >= StartDate &&
                        week.SaturdayDate + TimeSpan.FromDays(day) <= EndDate)
                        yield return week.DailySchedules[day];
            }
        }

        public IEnumerable<LeaveEntry> EnumerateLeave(DateTime StartDate, DateTime EndDate)
        {
            foreach (var day in EnumerateDays(StartDate, EndDate))
                foreach (var entry in day.ReliefDays)
                    yield return entry;
        }

        public void SaveData()
        {
            var writer = new System.IO.StreamWriter("data.txt");
            writer.Write("@ This file was generated by the Leave Wizard. Modifying this file could cause loss of data. @\n");
            for (var i = 0; i < Weeks.Count; ++i)
            {
                if (String.IsNullOrEmpty(Weeks[i].EffectiveChanges)) continue;
                writer.Write(i);
                writer.Write(" ");
                writer.Write(Weeks[i].EffectiveChanges);
                writer.WriteLine(";");
            }

            writer.Close();
        }

        public void LoadData()
        {
            try
            {
                Weeks = new List<WeekData>();
                CurrentWeek = 0;

                if (!System.IO.File.Exists("data.txt"))
                {
                    Weeks.Add(new WeekData());
                    return;
                }

                var text = System.IO.File.ReadAllText("data.txt").Trim();
                var stream = new StringIterator(text);

                if (!stream.AtEnd && stream.Next == '@')
                {
                    stream.Advance();
                    while (!stream.AtEnd && stream.Next != '@') stream.Advance();
                    stream.Advance();
                }

                while (!stream.AtEnd)
                {
                    var weekId = 0;
                    var weekData = "";
                    SkipWhitespace(stream);
                    ParseWeek(stream, out weekId, out weekData);

                    while (weekId >= Weeks.Count) Weeks.Add(new WeekData());
                    Weeks[weekId].EffectiveChanges = weekData;
                }
            }
            catch (Exception e)
            {
                System.Windows.MessageBox.Show(String.Format("An error has occured while loading saved data.\n{0}\nLoading will be aborted to preserve your existing data. To discard your saved data, delete 'data.txt' found in the folder where you installed Leave Wizard. It is likely that your existing data has been corrupted, but it might be possible to save it.", e.Message), "Critical error!", System.Windows.MessageBoxButton.OK);
                throw e;
            }
        }

        private void SkipWhitespace(StringIterator Iter)
        {
            while (!Iter.AtEnd && (Iter.Next == ' ' || Iter.Next == '\n' || Iter.Next == '\t' || Iter.Next == '\r'))
                Iter.Advance();
        }

        private static void ParseWeek(StringIterator Stream, out int WeekId, out String WeekData)
        {
            WeekId = 0;
            WeekData = "";

            var idString = "";
            while (!Stream.AtEnd && Stream.Next >= '0' && Stream.Next <= '9')
            {
                idString += (char)Stream.Next;
                Stream.Advance();
            }

            if (String.IsNullOrEmpty(idString)) return;

            var dataString = "";
            while (!Stream.AtEnd && Stream.Next != ';')
            {
                dataString += (char)Stream.Next;
                Stream.Advance();
            }

            Stream.Advance();

            WeekId = Convert.ToInt32(idString);
            WeekData = dataString;
        }
    }

}
