using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LeaveWizard
{
    public partial class LeaveChart
    {
        public void SaveData()
        {
            var writer = new System.IO.StreamWriter("data.txt");
            writer.Write("@ This file was generated by the Leave Wizard. Modifying this file could cause loss of data. @\n");
            for (var i = 0; i < Weeks.Count; ++i)
            {
                if (String.IsNullOrEmpty(Weeks[i].EffectiveChanges)) continue;
                writer.Write(i);
                writer.Write(" ");
                writer.Write(Weeks[i].EffectiveChanges);
                writer.WriteLine(";");
            }

            writer.Close();
        }

    }

}
